<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["name"=>"Afghanistan","code"=>"AF","languages"=>["prs","pus","tuk"],"flag"=>"🇦🇫"],
            ["name"=>"Albania","code"=>"AL","languages"=>["sqi"],"flag"=>"🇦🇱"],
            ["name"=>"Algeria","code"=>"DZ","languages"=>["ara"],"flag"=>"🇩🇿"],
            ["name"=>"American Samoa","code"=>"AS","languages"=>["eng","smo"],"flag"=>"🇦🇸"],
            ["name"=>"Andorra","code"=>"AD","languages"=>["cat"],"flag"=>"🇦🇩"],
            ["name"=>"Angola","code"=>"AO","languages"=>["por"],"flag"=>"🇦🇴"],
            ["name"=>"Anguilla","code"=>"AI","languages"=>["eng"],"flag"=>"🇦🇮"],
            ["name"=>"Antarctica","code"=>"AQ","languages"=>["eng"],"flag"=>"🇦🇶"],
            ["name"=>"Antigua and Barbuda","code"=>"AG","languages"=>["eng"],"flag"=>"🇦🇬"],
            ["name"=>"Argentina","code"=>"AR","languages"=>["grn","spa"],"flag"=>"🇦🇷"],
            ["name"=>"Armenia","code"=>"AM","languages"=>["hye"],"flag"=>"🇦🇲"],
            ["name"=>"Aruba","code"=>"AW","languages"=>["nld","pap"],"flag"=>"🇦🇼"],
            ["name"=>"Australia","code"=>"AU","languages"=>["eng"],"flag"=>"🇦🇺"],
            ["name"=>"Austria","code"=>"AT","languages"=>["deu"],"flag"=>"🇦🇹"],
            ["name"=>"Azerbaijan","code"=>"AZ","languages"=>["aze","rus"],"flag"=>"🇦🇿"],
            ["name"=>"Bahamas","code"=>"BS","languages"=>["eng"],"flag"=>"🇧🇸"],
            ["name"=>"Bahrain","code"=>"BH","languages"=>["ara"],"flag"=>"🇧🇭"],
            ["name"=>"Bangladesh","code"=>"BD","languages"=>["ben"],"flag"=>"🇧🇩"],
            ["name"=>"Barbados","code"=>"BB","languages"=>["eng"],"flag"=>"🇧🇧"],
            ["name"=>"Belarus","code"=>"BY","languages"=>["bel","rus"],"flag"=>"🇧🇾"],
            ["name"=>"Belgium","code"=>"BE","languages"=>["deu","fra","nld"],"flag"=>"🇧🇪"],
            ["name"=>"Belize","code"=>"BZ","languages"=>["bjz","eng","spa"],"flag"=>"🇧🇿"],
            ["name"=>"Benin","code"=>"BJ","languages"=>["fra"],"flag"=>"🇧🇯"],
            ["name"=>"Bermuda","code"=>"BM","languages"=>["eng"],"flag"=>"🇧🇲"],
            ["name"=>"Bhutan","code"=>"BT","languages"=>["dzo"],"flag"=>"🇧🇹"],
            ["name"=>"Bolivia","code"=>"BO","languages"=>["aym","grn","que","spa"],"flag"=>"🇧🇴"],
            ["name"=>"Bonaire","code"=>"BQ","languages"=>["eng","nld","pap"],"flag"=>"🇧🇶"],
            ["name"=>"Bosnia and Herzegovina","code"=>"BA","languages"=>["bos","hrv","srp"],"flag"=>"🇧🇦"],
            ["name"=>"Botswana","code"=>"BW","languages"=>["eng","tsn"],"flag"=>"🇧🇼"],
            ["name"=>"Bouvet Island","code"=>"BV","languages"=>["nor"],"flag"=>"🇧🇻"],
            ["name"=>"Brazil","code"=>"BR","languages"=>["por"],"flag"=>"🇧🇷"],
            ["name"=>"British Indian Ocean Territory","code"=>"IO","languages"=>["eng"],"flag"=>"🇮🇴"],
            ["name"=>"British Virgin Islands","code"=>"VG","languages"=>["eng"],"flag"=>"🇻🇬"],
            ["name"=>"Brunei","code"=>"BN","languages"=>["msa"],"flag"=>"🇧🇳"],
            ["name"=>"Bulgaria","code"=>"BG","languages"=>["bul"],"flag"=>"🇧🇬"],
            ["name"=>"Burkina Faso","code"=>"BF","languages"=>["fra"],"flag"=>"🇧🇫"],
            ["name"=>"Burundi","code"=>"BI","languages"=>["fra","run"],"flag"=>"🇧🇮"],
            ["name"=>"Cambodia","code"=>"KH","languages"=>["khm"],"flag"=>"🇰🇭"],
            ["name"=>"Cameroon","code"=>"CM","languages"=>["eng","fra"],"flag"=>"🇨🇲"],
            ["name"=>"Canada","code"=>"CA","languages"=>["eng","fra"],"flag"=>"🇨🇦"],
            ["name"=>"Cape Verde","code"=>"CV","languages"=>["por"],"flag"=>"🇨🇻"],
            ["name"=>"Cayman Islands","code"=>"KY","languages"=>["eng"],"flag"=>"🇰🇾"],
            ["name"=>"Central African Republic","code"=>"CF","languages"=>["fra","sag"],"flag"=>"🇨🇫"],
            ["name"=>"Chad","code"=>"TD","languages"=>["ara","fra"],"flag"=>"🇹🇩"],
            ["name"=>"Chile","code"=>"CL","languages"=>["spa"],"flag"=>"🇨🇱"],
            ["name"=>"China","code"=>"CN","languages"=>["zho"],"flag"=>"🇨🇳"],
            ["name"=>"Christmas Island","code"=>"CX","languages"=>["eng"],"flag"=>"🇨🇽"],
            ["name"=>"Cocos (Keeling) Islands","code"=>"CC","languages"=>["eng"],"flag"=>"🇨🇨"],
            ["name"=>"Colombia","code"=>"CO","languages"=>["spa"],"flag"=>"🇨🇴"],
            ["name"=>"Comoros","code"=>"KM","languages"=>["ara","fra","zdj"],"flag"=>"🇰🇲"],
            ["name"=>"Cook Islands","code"=>"CK","languages"=>["eng","rar"],"flag"=>"🇨🇰"],
            ["name"=>"Costa Rica","code"=>"CR","languages"=>["spa"],"flag"=>"🇨🇷"],
            ["name"=>"Croatia","code"=>"HR","languages"=>["hrv"],"flag"=>"🇭🇷"],
            ["name"=>"Cuba","code"=>"CU","languages"=>["spa"],"flag"=>"🇨🇺"],
            ["name"=>"Curacao","code"=>"CW","languages"=>["eng","nld","pap"],"flag"=>"🇨🇼"],
            ["name"=>"Cyprus","code"=>"CY","languages"=>["ell","tur"],"flag"=>"🇨🇾"],
            ["name"=>"Czech Republic","code"=>"CZ","languages"=>["ces","slk"],"flag"=>"🇨🇿"],
            ["name"=>"Democratic Republic of the Congo","code"=>"CD","languages"=>["fra","kon","lin","lua","swa"],"flag"=>"🇨🇩"],
            ["name"=>"Denmark","code"=>"DK","languages"=>["dan"],"flag"=>"🇩🇰"],
            ["name"=>"Djibouti","code"=>"DJ","languages"=>["ara","fra"],"flag"=>"🇩🇯"],
            ["name"=>"Dominica","code"=>"DM","languages"=>["eng"],"flag"=>"🇩🇲"],
            ["name"=>"Dominican Republic","code"=>"DO","languages"=>["spa"],"flag"=>"🇩🇴"],
            ["name"=>"East Timor","code"=>"TL","languages"=>["por","tet"],"flag"=>"🇹🇱"],
            ["name"=>"Ecuador","code"=>"EC","languages"=>["spa"],"flag"=>"🇪🇨"],
            ["name"=>"Egypt","code"=>"EG","languages"=>["ara"],"flag"=>"🇪🇬"],
            ["name"=>"El Salvador","code"=>"SV","languages"=>["spa"],"flag"=>"🇸🇻"],
            ["name"=>"Equatorial Guinea","code"=>"GQ","languages"=>["fra","por","spa"],"flag"=>"🇬🇶"],
            ["name"=>"Eritrea","code"=>"ER","languages"=>["ara","eng","tir"],"flag"=>"🇪🇷"],
            ["name"=>"Estonia","code"=>"EE","languages"=>["est"],"flag"=>"🇪🇪"],
            ["name"=>"Ethiopia","code"=>"ET","languages"=>["amh"],"flag"=>"🇪🇹"],
            ["name"=>"Falkland Islands","code"=>"FK","languages"=>["eng"],"flag"=>"🇫🇰"],
            ["name"=>"Faroe Islands","code"=>"FO","languages"=>["dan","fao"],"flag"=>"🇫🇴"],
            ["name"=>"Fiji","code"=>"FJ","languages"=>["eng","fij","hif"],"flag"=>"🇫🇯"],
            ["name"=>"Finland","code"=>"FI","languages"=>["fin","swe"],"flag"=>"🇫🇮"],
            ["name"=>"France","code"=>"FR","languages"=>["fra"],"flag"=>"🇫🇷"],
            ["name"=>"French Guiana","code"=>"GF","languages"=>["fra"],"flag"=>"🇬🇫"],
            ["name"=>"French Polynesia","code"=>"PF","languages"=>["fra"],"flag"=>"🇵🇫"],
            ["name"=>"French Southern Territories","code"=>"TF","languages"=>["fra"],"flag"=>"🇹🇫"],
            ["name"=>"Gabon","code"=>"GA","languages"=>["fra"],"flag"=>"🇬🇦"],
            ["name"=>"Gambia","code"=>"GM","languages"=>["eng"],"flag"=>"🇬🇲"],
            ["name"=>"Georgia","code"=>"GE","languages"=>["kat"],"flag"=>"🇬🇪"],
            ["name"=>"Germany","code"=>"DE","languages"=>["deu"],"flag"=>"🇩🇪"],
            ["name"=>"Ghana","code"=>"GH","languages"=>["eng"],"flag"=>"🇬🇭"],
            ["name"=>"Gibraltar","code"=>"GI","languages"=>["eng"],"flag"=>"🇬🇮"],
            ["name"=>"Greece","code"=>"GR","languages"=>["ell"],"flag"=>"🇬🇷"],
            ["name"=>"Greenland","code"=>"GL","languages"=>["kal"],"flag"=>"🇬🇱"],
            ["name"=>"Grenada","code"=>"GD","languages"=>["eng"],"flag"=>"🇬🇩"],
            ["name"=>"Guadeloupe","code"=>"GP","languages"=>["fra"],"flag"=>"🇬🇵"],
            ["name"=>"Guam","code"=>"GU","languages"=>["cha","eng","spa"],"flag"=>"🇬🇺"],
            ["name"=>"Guatemala","code"=>"GT","languages"=>["spa"],"flag"=>"🇬🇹"],
            ["name"=>"Guernsey","code"=>"GG","languages"=>["eng","fra","nfr"],"flag"=>"🇬🇬"],
            ["name"=>"Guinea","code"=>"GN","languages"=>["fra"],"flag"=>"🇬🇳"],
            ["name"=>"Guinea-Bissau","code"=>"GW","languages"=>["por","pov"],"flag"=>"🇬🇼"],
            ["name"=>"Guyana","code"=>"GY","languages"=>["eng"],"flag"=>"🇬🇾"],
            ["name"=>"Haiti","code"=>"HT","languages"=>["fra","hat"],"flag"=>"🇭🇹"],
            ["name"=>"Heard Island and McDonald Islands","code"=>"HM","languages"=>["eng"],"flag"=>"🇭🇲"],
            ["name"=>"Honduras","code"=>"HN","languages"=>["spa"],"flag"=>"🇭🇳"],
            ["name"=>"Hong Kong","code"=>"HK","languages"=>["eng","zho"],"flag"=>"🇭🇰"],
            ["name"=>"Hungary","code"=>"HU","languages"=>["hun"],"flag"=>"🇭🇺"],
            ["name"=>"Iceland","code"=>"IS","languages"=>["isl"],"flag"=>"🇮🇸"],
            ["name"=>"India","code"=>"IN","languages"=>["eng","hin","tam"],"flag"=>"🇮🇳"],
            ["name"=>"Indonesia","code"=>"ID","languages"=>["ind"],"flag"=>"🇮🇩"],
            ["name"=>"Iran","code"=>"IR","languages"=>["fas"],"flag"=>"🇮🇷"],
            ["name"=>"Iraq","code"=>"IQ","languages"=>["ara","arc","ckb"],"flag"=>"🇮🇶"],
            ["name"=>"Ireland","code"=>"IE","languages"=>["eng","gle"],"flag"=>"🇮🇪"],
            ["name"=>"Isle of Man","code"=>"IM","languages"=>["eng","glv"],"flag"=>"🇮🇲"],
            ["name"=>"Israel","code"=>"IL","languages"=>["ara","heb"],"flag"=>"🇮🇱"],
            ["name"=>"Italy","code"=>"IT","languages"=>["ita"],"flag"=>"🇮🇹"],
            ["name"=>"Ivory Coast","code"=>"CI","languages"=>["fra"],"flag"=>"🇨🇮"],
            ["name"=>"Jamaica","code"=>"JM","languages"=>["eng","jam"],"flag"=>"🇯🇲"],
            ["name"=>"Japan","code"=>"JP","languages"=>["jpn"],"flag"=>"🇯🇵"],
            ["name"=>"Jersey","code"=>"JE","languages"=>["eng","fra","nrf"],"flag"=>"🇯🇪"],
            ["name"=>"Jordan","code"=>"JO","languages"=>["ara"],"flag"=>"🇯🇴"],
            ["name"=>"Kazakhstan","code"=>"KZ","languages"=>["kaz","rus"],"flag"=>"🇰🇿"],
            ["name"=>"Kenya","code"=>"KE","languages"=>["eng","swa"],"flag"=>"🇰🇪"],
            ["name"=>"Kiribati","code"=>"KI","languages"=>["eng","gil"],"flag"=>"🇰🇮"],
            ["name"=>"Kosovo","code"=>"XK","languages"=>["sqi","srp"],"flag"=>"🇽🇰"],
            ["name"=>"Kuwait","code"=>"KW","languages"=>["ara"],"flag"=>"🇰🇼"],
            ["name"=>"Kyrgyzstan","code"=>"KG","languages"=>["kir","rus"],"flag"=>"🇰🇬"],
            ["name"=>"Laos","code"=>"LA","languages"=>["lao"],"flag"=>"🇱🇦"],
            ["name"=>"Latvia","code"=>"LV","languages"=>["lav"],"flag"=>"🇱🇻"],
            ["name"=>"Lebanon","code"=>"LB","languages"=>["ara","fra"],"flag"=>"🇱🇧"],
            ["name"=>"Lesotho","code"=>"LS","languages"=>["eng","sot"],"flag"=>"🇱🇸"],
            ["name"=>"Liberia","code"=>"LR","languages"=>["eng"],"flag"=>"🇱🇷"],
            ["name"=>"Libya","code"=>"LY","languages"=>["ara"],"flag"=>"🇱🇾"],
            ["name"=>"Liechtenstein","code"=>"LI","languages"=>["deu"],"flag"=>"🇱🇮"],
            ["name"=>"Lithuania","code"=>"LT","languages"=>["lit"],"flag"=>"🇱🇹"],
            ["name"=>"Luxembourg","code"=>"LU","languages"=>["deu","fra","ltz"],"flag"=>"🇱🇺"],
            ["name"=>"Macao","code"=>"MO","languages"=>["por","zho"],"flag"=>"🇲🇴"],
            ["name"=>"Madagascar","code"=>"MG","languages"=>["fra","mlg"],"flag"=>"🇲🇬"],
            ["name"=>"Malawi","code"=>"MW","languages"=>["eng","nya"],"flag"=>"🇲🇼"],
            ["name"=>"Malaysia","code"=>"MY","languages"=>["eng","msa"],"flag"=>"🇲🇾"],
            ["name"=>"Maldives","code"=>"MV","languages"=>["div"],"flag"=>"🇲🇻"],
            ["name"=>"Mali","code"=>"ML","languages"=>["fra"],"flag"=>"🇲🇱"],
            ["name"=>"Malta","code"=>"MT","languages"=>["eng","mlt"],"flag"=>"🇲🇹"],
            ["name"=>"Marshall Islands","code"=>"MH","languages"=>["eng","mah"],"flag"=>"🇲🇭"],
            ["name"=>"Martinique","code"=>"MQ","languages"=>["fra"],"flag"=>"🇲🇶"],
            ["name"=>"Mauritania","code"=>"MR","languages"=>["ara"],"flag"=>"🇲🇷"],
            ["name"=>"Mauritius","code"=>"MU","languages"=>["eng","fra","mfe"],"flag"=>"🇲🇺"],
            ["name"=>"Mayotte","code"=>"YT","languages"=>["fra"],"flag"=>"🇾🇹"],
            ["name"=>"Mexico","code"=>"MX","languages"=>["spa"],"flag"=>"🇲🇽"],
            ["name"=>"Micronesia","code"=>"FM","languages"=>["eng"],"flag"=>"🇫🇲"],
            ["name"=>"Moldova","code"=>"MD","languages"=>["ron"],"flag"=>"🇲🇩"],
            ["name"=>"Monaco","code"=>"MC","languages"=>["fra"],"flag"=>"🇲🇨"],
            ["name"=>"Mongolia","code"=>"MN","languages"=>["mon"],"flag"=>"🇲🇳"],
            ["name"=>"Montenegro","code"=>"ME","languages"=>["cnr","srp","bos","sqi","hrv"],"flag"=>"🇲🇪"],
            ["name"=>"Montserrat","code"=>"MS","languages"=>["eng"],"flag"=>"🇲🇸"],
            ["name"=>"Morocco","code"=>"MA","languages"=>["ara","zgh"],"flag"=>"🇲🇦"],
            ["name"=>"Mozambique","code"=>"MZ","languages"=>["por"],"flag"=>"🇲🇿"],
            ["name"=>"Myanmar (Burma)","code"=>"MM","languages"=>["mya"],"flag"=>"🇲🇲"],
            ["name"=>"Namibia","code"=>"NA","languages"=>["afr","deu","eng","her","hgm","kwn","loz","ndo","tsn"],"flag"=>"🇳🇦"],
            ["name"=>"Nauru","code"=>"NR","languages"=>["eng","nau"],"flag"=>"🇳🇷"],
            ["name"=>"Nepal","code"=>"NP","languages"=>["nep"],"flag"=>"🇳🇵"],
            ["name"=>"Netherlands","code"=>"NL","languages"=>["nld"],"flag"=>"🇳🇱"],
            ["name"=>"New Caledonia","code"=>"NC","languages"=>["fra"],"flag"=>"🇳🇨"],
            ["name"=>"New Zealand","code"=>"NZ","languages"=>["eng","mri","nzs"],"flag"=>"🇳🇿"],
            ["name"=>"Nicaragua","code"=>"NI","languages"=>["spa"],"flag"=>"🇳🇮"],
            ["name"=>"Niger","code"=>"NE","languages"=>["fra"],"flag"=>"🇳🇪"],
            ["name"=>"Nigeria","code"=>"NG","languages"=>["eng"],"flag"=>"🇳🇬"],
            ["name"=>"Niue","code"=>"NU","languages"=>["eng","niu"],"flag"=>"🇳🇺"],
            ["name"=>"Norfolk Island","code"=>"NF","languages"=>["eng","pih"],"flag"=>"🇳🇫"],
            ["name"=>"North Korea","code"=>"KP","languages"=>["kor"],"flag"=>"🇰🇵"],
            ["name"=>"North Macedonia","code"=>"MK","languages"=>["mkd"],"flag"=>"🇲🇰"],
            ["name"=>"Northern Mariana Islands","code"=>"MP","languages"=>["cal","cha","eng"],"flag"=>"🇲🇵"],
            ["name"=>"Norway","code"=>"NO","languages"=>["nor"],"flag"=>"🇳🇴"],
            ["name"=>"Oman","code"=>"OM","languages"=>["ara"],"flag"=>"🇴🇲"],
            ["name"=>"Pakistan","code"=>"PK","languages"=>["eng","urd"],"flag"=>"🇵🇰"],
            ["name"=>"Palau","code"=>"PW","languages"=>["eng","pau"],"flag"=>"🇵🇼"],
            ["name"=>"Palestine","code"=>"PS","languages"=>["ara"],"flag"=>"🇵🇸"],
            ["name"=>"Panama","code"=>"PA","languages"=>["spa"],"flag"=>"🇵🇦"],
            ["name"=>"Papua New Guinea","code"=>"PG","languages"=>["eng","hmo","tpi"],"flag"=>"🇵🇬"],
            ["name"=>"Paraguay","code"=>"PY","languages"=>["grn","spa"],"flag"=>"🇵🇾"],
            ["name"=>"Peru","code"=>"PE","languages"=>["aym","que","spa"],"flag"=>"🇵🇪"],
            ["name"=>"Philippines","code"=>"PH","languages"=>["eng","fil"],"flag"=>"🇵🇭"],
            ["name"=>"Pitcairn Islands","code"=>"PN","languages"=>["eng"],"flag"=>"🇵🇳"],
            ["name"=>"Poland","code"=>"PL","languages"=>["pol"],"flag"=>"🇵🇱"],
            ["name"=>"Portugal","code"=>"PT","languages"=>["por"],"flag"=>"🇵🇹"],
            ["name"=>"Puerto Rico","code"=>"PR","languages"=>["eng","spa"],"flag"=>"🇵🇷"],
            ["name"=>"Qatar","code"=>"QA","languages"=>["ara"],"flag"=>"🇶🇦"],
            ["name"=>"Republic of the Congo","code"=>"CG","languages"=>["fra","kon","lin"],"flag"=>"🇨🇬"],
            ["name"=>"Romania","code"=>"RO","languages"=>["ron"],"flag"=>"🇷🇴"],
            ["name"=>"Russia","code"=>"RU","languages"=>["rus"],"flag"=>"🇷🇺"],
            ["name"=>"Rwanda","code"=>"RW","languages"=>["eng","fra","kin"],"flag"=>"🇷🇼"],
            ["name"=>"Réunion","code"=>"RE","languages"=>["fra"],"flag"=>"🇷🇪"],
            ["name"=>"Saint Barthélemy","code"=>"BL","languages"=>["fra"],"flag"=>"🇧🇱"],
            ["name"=>"Saint Helena","code"=>"SH","languages"=>["eng"],"flag"=>"🇸🇭"],
            ["name"=>"Saint Kitts and Nevis","code"=>"KN","languages"=>["eng"],"flag"=>"🇰🇳"],
            ["name"=>"Saint Lucia","code"=>"LC","languages"=>["eng"],"flag"=>"🇱🇨"],
            ["name"=>"Saint Martin","code"=>"MF","languages"=>["fra"],"flag"=>"🇲🇫"],
            ["name"=>"Saint Pierre and Miquelon","code"=>"PM","languages"=>["fra"],"flag"=>"🇵🇲"],
            ["name"=>"Saint Vincent and the Grenadines","code"=>"VC","languages"=>["eng"],"flag"=>"🇻🇨"],
            ["name"=>"Samoa","code"=>"WS","languages"=>["eng","smo"],"flag"=>"🇼🇸"],
            ["name"=>"San Marino","code"=>"SM","languages"=>["ita"],"flag"=>"🇸🇲"],
            ["name"=>"Saudi Arabia","code"=>"SA","languages"=>["ara"],"flag"=>"🇸🇦"],
            ["name"=>"Senegal","code"=>"SN","languages"=>["fra"],"flag"=>"🇸🇳"],
            ["name"=>"Serbia","code"=>"RS","languages"=>["srp"],"flag"=>"🇷🇸"],
            ["name"=>"Seychelles","code"=>"SC","languages"=>["crs","eng","fra"],"flag"=>"🇸🇨"],
            ["name"=>"Sierra Leone","code"=>"SL","languages"=>["eng"],"flag"=>"🇸🇱"],
            ["name"=>"Singapore","code"=>"SG","languages"=>["eng","msa","zho","tam"],"flag"=>"🇸🇬"],
            ["name"=>"Sint Maarten","code"=>"SX","languages"=>["eng","fra","nld"],"flag"=>"🇸🇽"],
            ["name"=>"Slovakia","code"=>"SK","languages"=>["slk","ces"],"flag"=>"🇸🇰"],
            ["name"=>"Slovenia","code"=>"SI","languages"=>["slv"],"flag"=>"🇸🇮"],
            ["name"=>"Solomon Islands","code"=>"SB","languages"=>["eng"],"flag"=>"🇸🇧"],
            ["name"=>"Somalia","code"=>"SO","languages"=>["ara","som"],"flag"=>"🇸🇴"],
            ["name"=>"South Africa","code"=>"ZA","languages"=>["afr","eng","nbl","nso","sot","ssw","tsn","tso","ven","xho","zul"],"flag"=>"🇿🇦"],
            ["name"=>"South Georgia and the South Sandwich Islands","code"=>"GS","languages"=>["eng"],"flag"=>"🇬🇸"],
            ["name"=>"South Korea","code"=>"KR","languages"=>["kor"],"flag"=>"🇰🇷"],
            ["name"=>"South Sudan","code"=>"SS","languages"=>["eng"],"flag"=>"🇸🇸"],
            ["name"=>"Spain","code"=>"ES","languages"=>["spa"],"flag"=>"🇪🇸"],
            ["name"=>"Sri Lanka","code"=>"LK","languages"=>["sin","tam"],"flag"=>"🇱🇰"],
            ["name"=>"Sudan","code"=>"SD","languages"=>["ara","eng"],"flag"=>"🇸🇩"],
            ["name"=>"Suriname","code"=>"SR","languages"=>["nld"],"flag"=>"🇸🇷"],
            ["name"=>"Svalbard and Jan Mayen","code"=>"SJ","languages"=>["nor"],"flag"=>"🇸🇯"],
            ["name"=>"Swaziland","code"=>"SZ","languages"=>["eng","ssw"],"flag"=>"🇸🇿"],
            ["name"=>"Sweden","code"=>"SE","languages"=>["swe"],"flag"=>"🇸🇪"],
            ["name"=>"Switzerland","code"=>"CH","languages"=>["deu","fra","ita"],"flag"=>"🇨🇭"],
            ["name"=>"Syria","code"=>"SY","languages"=>["ara"],"flag"=>"🇸🇾"],
            ["name"=>"São Tomé and Príncipe","code"=>"ST","languages"=>["por"],"flag"=>"🇸🇹"],
            ["name"=>"Taiwan","code"=>"TW","languages"=>["zho"],"flag"=>"🇹🇼"],
            ["name"=>"Tajikistan","code"=>"TJ","languages"=>["rus","tgk"],"flag"=>"🇹🇯"],
            ["name"=>"Tanzania","code"=>"TZ","languages"=>["eng","swa"],"flag"=>"🇹🇿"],
            ["name"=>"Thailand","code"=>"TH","languages"=>["tha"],"flag"=>"🇹🇭"],
            ["name"=>"Togo","code"=>"TG","languages"=>["fra"],"flag"=>"🇹🇬"],
            ["name"=>"Tokelau","code"=>"TK","languages"=>["eng","smo","tkl"],"flag"=>"🇹🇰"],
            ["name"=>"Tonga","code"=>"TO","languages"=>["eng","ton"],"flag"=>"🇹🇴"],
            ["name"=>"Trinidad and Tobago","code"=>"TT","languages"=>["eng"],"flag"=>"🇹🇹"],
            ["name"=>"Tunisia","code"=>"TN","languages"=>["ara"],"flag"=>"🇹🇳"],
            ["name"=>"Turkey","code"=>"TR","languages"=>["tur"],"flag"=>"🇹🇷"],
            ["name"=>"Turkmenistan","code"=>"TM","languages"=>["rus","tuk"],"flag"=>"🇹🇲"],
            ["name"=>"Turks and Caicos Islands","code"=>"TC","languages"=>["eng"],"flag"=>"🇹🇨"],
            ["name"=>"Tuvalu","code"=>"TV","languages"=>["eng","tvl"],"flag"=>"🇹🇻"],
            ["name"=>"U.S. Minor Outlying Islands","code"=>"UM","languages"=>["eng"],"flag"=>"🇺🇲"],
            ["name"=>"U.S. Virgin Islands","code"=>"VI","languages"=>["eng"],"flag"=>"🇻🇮"],
            ["name"=>"Uganda","code"=>"UG","languages"=>["eng","swa"],"flag"=>"🇺🇬"],
            ["name"=>"Ukraine","code"=>"UA","languages"=>["ukr"],"flag"=>"🇺🇦"],
            ["name"=>"United Arab Emirates","code"=>"AE","languages"=>["ara"],"flag"=>"🇦🇪"],
            ["name"=>"United Kingdom","code"=>"UK","languages"=>["eng"],"flag"=>"🇬🇧"],
            ["name"=>"United States","code"=>"US","languages"=>["eng","spa"],"flag"=>"🇺🇸"],
            ["name"=>"Uruguay","code"=>"UY","languages"=>["spa"],"flag"=>"🇺🇾"],
            ["name"=>"Uzbekistan","code"=>"UZ","languages"=>["rus","uzb"],"flag"=>"🇺🇿"],
            ["name"=>"Vanuatu","code"=>"VU","languages"=>["bis","eng","fra"],"flag"=>"🇻🇺"],
            ["name"=>"Vatican City","code"=>"VA","languages"=>["ita","lat"],"flag"=>"🇻🇦"],
            ["name"=>"Venezuela","code"=>"VE","languages"=>["spa"],"flag"=>"🇻🇪"],
            ["name"=>"Vietnam","code"=>"VN","languages"=>["vie"],"flag"=>"🇻🇳"],
            ["name"=>"Wallis and Futuna","code"=>"WF","languages"=>["fra"],"flag"=>"🇼🇫"],
            ["name"=>"Western Sahara","code"=>"EH","languages"=>["zgh","mey","spa"],"flag"=>"🇪🇭"],
            ["name"=>"Yemen","code"=>"YE","languages"=>["ara"],"flag"=>"🇾🇪"],
            ["name"=>"Zambia","code"=>"ZM","languages"=>["eng"],"flag"=>"🇿🇲"],
            ["name"=>"Zimbabwe","code"=>"ZW","languages"=>["bwg","eng","kck","hio","ndc","nde","nya","sna","sot","toi","tsn","tso","ven","xho","zib"],"flag"=>"🇿🇼"],
            ["name"=>"Åland","code"=>"AX","languages"=>["swe"],"flag"=>"🇦🇽"]
        ];

        foreach ($data as $countryData) {
            $lowercasedCountryCode = strtolower($countryData["code"]);
            DB::table('countries')->insert([
                'code' => $lowercasedCountryCode,
                'name' => $countryData["name"],
                'flag' => $countryData["flag"]
            ]);
        }
    }
}